apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform_basic
  annotations:
    github.com/project-slug: showcante/terraform_basic
spec:
  type: other
  lifecycle: unknown
  owner: team-a
